update dependencies

diff --git a/evolution-services b/evolution-services
--- a/evolution-services
+++ b/evolution-services
@@ -1,4 +1,6 @@
 #!/bin/bash
+unset IFS
+set -eufEo pipefail
 
 ## Improved version of the script at https://askubuntu.com/a/1068932
 ##
@@ -10,35 +12,30 @@
 
 myname=$(basename "$0")
 
-promp_usage()
-{
+promp_usage() {
     echo "Usage: $myname ( --enable | --disable )"
     exit 1
 }
 
-if [ $# -ne 1 ]
-then
+if [ $# -ne 1 ]; then
     promp_usage
 fi
 
 SERVICES_HOME="/usr/share/dbus-1/services"
 DISABLED_DIR="$SERVICES_HOME/disabled"
 
-
-die()
-{
+die() {
     local errorCode=$1
     local errorMessage="$2"
 
     echo "$errorMessage"
-    exit $errorCode
+    exit "$errorCode"
 }
 
-check_assumptions()
-{
+check_assumptions() {
     # Make sure that we are running as root and that the
     # services directory didn't change!
-    if ! [ $(id -u) = 0 ]; then
+    if ! [ "$(id -u)" = 0 ]; then
         die -1 "Script must be run as root or sudo.  Exiting..."
     fi
 
@@ -47,27 +44,24 @@ check_assumptions()
     fi
 }
 
-find_evolution_services()
-{
+find_evolution_services() {
     find "$SERVICES_HOME" -maxdepth 1 \
-                          -type f \
-                          -name "org.gnome.evolution.dataserver.*" \
-                          ! -name "*.bak" \
-                          -printf "%f\0"
+        -type f \
+        -name "org.gnome.evolution.dataserver.*" \
+        ! -name "*.bak" \
+        -printf "%f\0"
 }
 
-disable-services()
-{
+disable-services() {
     mkdir -p "$DISABLED_DIR"
 
-    find_evolution_services | while IFS= read -r -d $'\0' servicename
-    do
+    find_evolution_services | while IFS= read -r -d $'\0' servicename; do
         # Tell dpkg/apt to update the file in DISABLED_DIR instead
         # of the one in SERVICES_HOME
-        dpkg-divert --quiet --divert "$DISABLED_DIR/$servicename" --rename --add "$SERVICES_HOME/$servicename" \
-            || die -3 "Unable to divert service $servicename."
+        dpkg-divert --quiet --divert "$DISABLED_DIR/$servicename" --rename --add "$SERVICES_HOME/$servicename" ||
+            die -3 "Unable to divert service $servicename."
 
-        ln -snf /dev/null  "$SERVICES_HOME/$servicename"
+        ln -snf /dev/null "$SERVICES_HOME/$servicename"
         echo "Disabled service $servicename"
     done
 
@@ -80,16 +74,14 @@ disable-services()
     echo "Please restart for changes to take effect."
 }
 
-enable-services()
-{
+enable-services() {
     chmod a+x /usr/libexec/evolution-addressbook-factory
     chmod a+x /usr/libexec/evolution-calendar-factory
     chmod a+x /usr/libexec/evolution-data-server/evolution-alarm-notify
     chmod a+x /usr/libexec/evolution-source-registry
 
     local servicename servicefile
-    for servicename in AddressBook Calendar Sources UserPrompter
-    do
+    for servicename in AddressBook Calendar Sources UserPrompter; do
         local servicefile=org.gnome.evolution.dataserver."$servicename".service
         rm "$SERVICES_HOME/$servicefile"
         dpkg-divert --rename --remove "$SERVICES_HOME/$servicefile"
@@ -98,7 +90,7 @@ enable-services()
 
 check_assumptions
 case "$1" in
-    --enable) enable-services ;;
-    --disable) disable-services ;;
-    *) promp_usage ;;
+--enable) enable-services ;;
+--disable) disable-services ;;
+*) promp_usage ;;
 esac
